name: build-darwin
on:
  workflow_call:
    inputs:
      GOARCH:
        required: true
        type: string
    outputs:
      artifact:
        value: resonance.darwin.${{ inputs.GOARCH }}.gz
jobs:
  build:
    runs-on: macos-latest
    env:
        GOOS: darwin
        GOARCH: ${{ inputs.GOARCH }}
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      # Make
      - name: Setup Make
        run: brew install make
        shell: bash
      # Cache
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/
          key: darwin-${{ inputs.GOARCH }}-${{ hashFiles('**/go.sum', '**/*.go') }}
          restore-keys: darwin-${{ inputs.GOARCH }}-
      # Build
      - name: Build
        run: |
          GOOS=darwin GOARCH=${{ inputs.GOARCH }} gmake ci V=1
        shell: bash
      # Git Status
      - name: git status
        run: |
          GIT_STATUS="$(git status --porcelain)"
          if [ -n "$GIT_STATUS" ] ; then
            echo git status
            echo "$GIT_STATUS"
            echo git diff
            git diff
            exit 1
          fi
        shell: bash
      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: resonance.darwin.${{ inputs.GOARCH }}.gz
          path: resonance.darwin.${{ inputs.GOARCH }}.gz