name: build-linux
on:
  workflow_call:
    inputs:
      upload-artifact:
        required: false
        type: boolean
        default: false
      GOARCH:
        required: true
        type: string
    outputs:
      artifact:
        value: resonance.linux.${{ inputs.GOARCH }}.gz
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GOOS: linux
        GOARCH: ${{ inputs.GOARCH }}
        XDG_CACHE_HOME: /tmp/XDG_CACHE_HOME
        DOCKER_PLATFORM: linux/${{ inputs.GOARCH }}
        GO_TEST_BINARY_FLAGS_EXTRA: -v
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
      # Architecture support
      - name: Architecture support
        if: ${{ inputs.GOARCH != '386' && inputs.GOARCH != 'amd64' }}
        run: |
          sudo apt-get update
          sudo apt-get -y install binfmt-support qemu-user-static
        shell: bash
      # Cache restore
      - name: Cache restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: linux-${{ inputs.GOARCH }}-${{ hashFiles('**/go.sum', '**/*.go') }}
          restore-keys: linux-${{ inputs.GOARCH }}-
      # Build
      - name: Build
        run: |
          ./build.sh ci
        shell: bash
      # Git Status
      - name: git status
        run: |
          GIT_STATUS="$(git status --porcelain)"
          if [ -n "$GIT_STATUS" ] ; then
            echo Error: Build process modified files under version control!
            echo git status
            echo "$GIT_STATUS"
            echo git diff
            git diff
            exit 1
          fi
        shell: bash
      # Cache save
      - name: Cache save
        uses: actions/cache/save@v4
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: linux-${{ inputs.GOARCH }}-${{ hashFiles('**/go.sum', '**/*.go') }}
      # Gzip
      - name: Gzip
        run: gzip resonance.linux.${{ inputs.GOARCH }}
        shell: bash
      # Upload
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload-artifact == true }}
        with:
          name: resonance.linux.${{ inputs.GOARCH }}.gz
          path: resonance.linux.${{ inputs.GOARCH }}.gz
          if-no-files-found: error
      # Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.0
        with:
          file: cover.lcov
          flag-name: linux.${{ inputs.GOARCH }}
          parallel: true
          allow-empty: true
      # Clean
      - name: Clean
        run: ./build.sh clean
        shell: bash
      # Git ls-files --others
      - name: git ls-files --others
        run: |
          GIT_LS_FILES_OTHERS="$(git ls-files --others)"
          if [ -n "$GIT_LS_FILES_OTHERS" ] ; then
            echo Error: Build clean left files behind!
            echo git ls-files --others
            echo "$GIT_LS_FILES_OTHERS"
            exit 1
          fi
        shell: bash