name: build-darwin
on:
  workflow_call:
    inputs:
      GOARCH:
        required: true
        type: string
    outputs:
      artifact:
        value: resonance.darwin.${{ inputs.GOARCH }}.gz
jobs:
  build:
    runs-on: macos-latest
    env:
        GOOS: darwin
        GOARCH: ${{ inputs.GOARCH }}
        XDG_CACHE_HOME: /tmp/XDG_CACHE_HOME
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      # Make
      - name: Setup Make
        run: brew install make
        shell: bash
      # Cache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: /tmp/XDG_CACHE_HOME
          key: darwin-${{ inputs.GOARCH }}-${{ hashFiles('**/go.sum', '**/*.go') }}
          restore-keys: darwin-${{ inputs.GOARCH }}-
      # Build
      - name: Build (native)
        if: ${{ inputs.GOARCH == 'arm64' }}
        run: |
          GOOS=darwin GOARCH=${{ inputs.GOARCH }} XDG_CACHE_HOME=/tmp/XDG_CACHE_HOME gmake ci V=1
        shell: bash
      - name: Build (cross compile only)
        if: ${{ inputs.GOARCH != 'arm64' }}
        run: |
          GOOS=darwin GOARCH=${{ inputs.GOARCH }} gmake build V=1
        shell: bash
      # Gzip
      - name: Gzip
        run: gzip resonance.darwin.${{ inputs.GOARCH }}
        shell: bash
      # Git Status
      - name: git status
        run: |
          GIT_STATUS="$(git status --porcelain)"
          if [ -n "$GIT_STATUS" ] ; then
            echo git status
            echo "$GIT_STATUS"
            echo git diff
            git diff
            exit 1
          fi
        shell: bash
      # Upload
      - uses: actions/upload-artifact@v4
        with:
          name: resonance.darwin.${{ inputs.GOARCH }}.gz
          path: resonance.darwin.${{ inputs.GOARCH }}.gz
          if-no-files-found: error
      # Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        if: ${{ inputs.GOARCH == 'arm64' }}
        with:
          file: cover.lcov
          flag-name: darwin.${{ inputs.GOARCH }}
          parallel: true
          allow-empty: true
      # Clean
      - name: Clean
        run: gmake clean
        shell: bash
      # Git ls-files --others
      - name: git ls-files --others
        run: |
          GIT_LS_FILES_OTHERS="$(git ls-files --others)"
          if [ -n "$GIT_LS_FILES_OTHERS" ] ; then
            echo git ls-files --others
            echo "$GIT_LS_FILES_OTHERS"
            exit 1
          fi
        shell: bash