name: ci
on:
    pull_request:
        branches:
            - "master"
    push:
        branches:
            - "master"
        tags:
            - "v*"
concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    linux_386:
        uses: ./.github/workflows/build-linux.yaml
        with:
            upload-artifact: ${{ startsWith(github.ref, 'refs/tags/') }}
            GOARCH: 386
            runs-on: ubuntu-24.04
        secrets: inherit
    linux_amd64:
        uses: ./.github/workflows/build-linux.yaml
        with:
            upload-artifact: ${{ startsWith(github.ref, 'refs/tags/') }}
            GOARCH: amd64
            runs-on: ubuntu-24.04
        secrets: inherit
    linux_arm64:
        uses: ./.github/workflows/build-linux.yaml
        with:
            upload-artifact: ${{ startsWith(github.ref, 'refs/tags/') }}
            GOARCH: arm64
            runs-on: ubuntu-24.04-arm
        secrets: inherit
    darwin_amd64:
        uses: ./.github/workflows/build-darwin.yaml
        with:
            upload-artifact: ${{ startsWith(github.ref, 'refs/tags/') }}
            GOARCH: amd64
            runs-on: macos-13
        secrets: inherit
    darwin_arm64:
        uses: ./.github/workflows/build-darwin.yaml
        with:
            upload-artifact: ${{ startsWith(github.ref, 'refs/tags/') }}
            GOARCH: arm64
            runs-on: macos-14
        secrets: inherit
    release:
        concurrency: release
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        permissions:
            contents: write
        needs:
            - linux_386
            - linux_amd64
            - linux_arm64
            - darwin_amd64
            - darwin_arm64
        steps:
            - uses: actions/download-artifact@v4.1.7
              with:
                name: ${{ needs.linux_386.outputs.artifact }}
            - uses: actions/download-artifact@v4.1.7
              with:
                name: ${{ needs.linux_amd64.outputs.artifact }}
            - uses: actions/download-artifact@v4.1.7
              with:
                name: ${{ needs.linux_arm64.outputs.artifact }}
            - uses: actions/download-artifact@v4.1.7
              with:
                name: ${{ needs.darwin_amd64.outputs.artifact }}
            - uses: actions/download-artifact@v4.1.7
              with:
                name: ${{ needs.darwin_arm64.outputs.artifact }}
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: |
                    ${{ needs.linux_386.outputs.artifact }}
                    ${{ needs.linux_amd64.outputs.artifact }}
                    ${{ needs.linux_arm64.outputs.artifact }}
                    ${{ needs.darwin_amd64.outputs.artifact }}
                    ${{ needs.darwin_arm64.outputs.artifact }}
            - name: Add to pkg.go.dev
              # https://pkg.go.dev/about#adding-a-package
              run: |
                set -e
                curl -v https://proxy.golang.org/github.com/fornellas/resonance/@v/$(git describe --tags).info
              shell: bash
    coveralls:
        needs:
            - linux_386
            - linux_amd64
            - linux_arm64
            - darwin_amd64
            - darwin_arm64
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@v2.3.4
              with:
                parallel-finished: true
