name: pull_request
on:
  pull_request:
    branches:
      - '*'
jobs:
  pull_request:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build