name: pull_request
on:
  pull_request:
    branches:
      - "master"
      - "spr/master/*"
jobs:
  linux_386:
    uses: ./.github/workflows/build-linux.yaml
    with:
      GOARCH: 386
      runs-on: ubuntu-24.04
    secrets: inherit
  linux_amd64:
    uses: ./.github/workflows/build-linux.yaml
    with:
      GOARCH: amd64
      runs-on: ubuntu-24.04
    secrets: inherit
  linux_arm64:
    uses: ./.github/workflows/build-linux.yaml
    with:
      GOARCH: arm64
      runs-on: ubuntu-24.04-arm
    secrets: inherit
  darwin_amd64:
    uses: ./.github/workflows/build-darwin.yaml
    with:
      GOARCH: amd64
      runs-on: macos-13
    secrets: inherit
  darwin_arm64:
    uses: ./.github/workflows/build-darwin.yaml
    with:
      GOARCH: arm64
      runs-on: macos-14
    secrets: inherit
  coveralls:
    needs:
      - linux_386
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.3.4
        with:
          parallel-finished: true
  spr:
    runs-on: ubuntu-latest
    steps:
      - name: Block PRs against spr/master/*
        id: check_base
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == spr/master/* ]]; then
            echo "Base branch seems to be part of a PR stack: this can't be merged directly. Details: https://github.com/ejoffe/spr."
            exit 1
          fi
