name: pull_request
on:
  pull_request:
    branches:
      - '*'
jobs:
  linux_386:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: 386
    secrets: inherit
  linux_amd64:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: amd64
    secrets: inherit
  linux_arm:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: arm
    secrets: inherit
  linux_arm64:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: arm64
    secrets: inherit