name: push
on:
  push:
    branches:
      - 'master'
    tags:
      - "v*"
concurrency: push
jobs:
  push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Compile
        id: compile
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e
          echo 'files<<EOF' >> $GITHUB_OUTPUT
          for GOARCH in 386 amd64 arm arm64
          do
            echo GOARCH=$GOARCH
            GOARCH=$GOARCH make build
            mv resonance resonance.$(go env GOOS).$GOARCH
            gzip resonance.$(go env GOOS).$GOARCH
            echo resonance.$(go env GOOS).${GOARCH}.gz >> $GITHUB_OUTPUT
          done
          echo EOF >> $GITHUB_OUTPUT
        shell: bash
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.compile.outputs.files }}
      - name: Add to pkg.go.dev
        if: startsWith(github.ref, 'refs/tags/')
        # https://pkg.go.dev/about#adding-a-package
        run: |
          set -e
          curl -v https://proxy.golang.org/github.com/fornellas/resonance/@v/$(git describe --tags).info
        shell: bash
