name: push
on:
  push:
    branches:
      - 'master'
    tags:
      - "v*"
concurrency: push
jobs:
  push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
      - name: Get GOOS
        id: goos
        run: |
          set -e
          echo "value=$(go env GOOS)" >> $GITHUB_OUTPUT
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
      - name: Get GOARCH
        id: goarch
        run: |
          set -e
          echo "value=$(go env GOARCH)" >> $GITHUB_OUTPUT
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
      - name: Define binary name
        id: binary_name
        run: |
          set -e
          echo "value=resonance.${{ steps.goos.outputs.value }}.${{ steps.goarch.outputs.value }}" >> $GITHUB_OUTPUT
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
      - name: Prepare binary
        run: |
          set -e
          mv resonance ${{ steps.binary_name.outputs.value }}
          gzip ${{ steps.binary_name.outputs.value }}
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.binary_name.outputs.value }}.gz