name: push
on:
  push:
    branches:
      - 'master'
    tags:
      - "v*"
jobs:
  linux_386:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: 386
      CODECOV_TOKEN: ${{ secret.CODECOV_TOKEN }}
  linux_amd64:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: amd64
      CODECOV_TOKEN: ${{ secret.CODECOV_TOKEN }}
  linux_arm:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: arm
      CODECOV_TOKEN: ${{ secret.CODECOV_TOKEN }}
  linux_arm64:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: arm64
      CODECOV_TOKEN: ${{ secret.CODECOV_TOKEN }}
  release:
    concurrency: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs:
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.linux_386.outputs.artifact }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.linux_amd64.outputs.artifact }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.linux_arm.outputs.artifact }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.linux_arm64.outputs.artifact }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ needs.linux_386.outputs.artifact }}
            ${{ needs.linux_amd64.outputs.artifact }}
            ${{ needs.linux_arm.outputs.artifact }}
            ${{ needs.linux_arm64.outputs.artifact }}
      - name: Add to pkg.go.dev
        # https://pkg.go.dev/about#adding-a-package
        run: |
          set -e
          curl -v https://proxy.golang.org/github.com/fornellas/resonance/@v/$(git describe --tags).info
        shell: bash