name: push
on:
  push:
    branches:
      - 'master'
    tags:
      - "v*"
concurrency: push
jobs:
  push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
      - name: Compile
        id: compile
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e
          echo 'files<<EOF' >> $GITHUB_OUTPUT
          for GOARCH in 386 amd64 arm arm64
          do
            GOARCH=$GOARCH make build
            mv resonance resonance.$(go env GOOS).$GOARCH
            gzip resonance.$(go env GOOS).$GOARCH
            echo resonance.$(go env GOOS).${GOARCH}.gz >> $GITHUB_OUTPUT
          done
        shell: bash
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.compile.output.files }}