name: update_deps
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  update_deps:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/build-linux.yaml
    with:
      GOARCH: amd64
      runs-on: ubuntu-24.04
      update-deps: true
      coveralls: false
    secrets: inherit
